modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="sly_adnanced_redstone"
version="9.4"
displayName="Sly Advanced redstone"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Slyfalco"
description='''
I knew there was more to redstone
'''

[[dependencies.sly_adnanced_redstone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"




